main:
  - name: About
    url: /#section-resume-biography-3
    weight: 10
  - name: Research
    url: /#research
    weight: 20
  - name: Exp
    url: /#experience
    weight: 30
  - name: Publications
    url: /#publications
    weight: 40
  - name: Additional Awards
    url: /#awards
    weight: 50
